name: SAM Build and Deploy
description: SAM Build and Deploy

inputs:
  environment:
    description: Environment
    required: true
  microservice-name:
    description: Microservice name
    required: true
  aws-account-id:
    description: AWS account id
    required: true
  aws-region:
    description: AWS Region
    required: true
  s3-bucket:
    description: S3 bucket
    required: true

runs:
  using: composite
  steps:
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v1

    - name: Build image
      id: build-image
      shell: bash
      run: >
        sam build
        --base-dir .
        --template-file ./infrastructure/infrastructure.yml
        
    - name: Deploy stack
      id: deploy-stack
      shell: bash
      run: >
        sam deploy
        --no-confirm-changeset
        --no-fail-on-empty-changeset
        --stack-name ${{ inputs.microservice-name }}-${{ inputs.environment }}
        --region ${{ inputs.aws-region }}
        --image-repository ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/doo/${{ inputs.microservice-name }}
        --s3-bucket ${{ inputs.s3-bucket }}
        --s3-prefix ${{ inputs.microservice-name }}
        --parameter-overrides Infrastructure=${{ inputs.environment }}
        --capabilities CAPABILITY_IAM
