name: Describe infrastructure events
inputs:
  microservice-name:
    description: Microservice short name
    required: true
  environment:
    description: Environment
    required: true
  cf-stack-name-suffix:
    description: CloudFormation stack name suffix with trailing '-' (e.g. -database)
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Describe infrastructure events
      shell: bash
      run: |
        aws cloudformation describe-stack-events --stack-name ${{ format('{0}-{1}{2}', inputs.microservice-name, inputs.environment, inputs.cf-stack-name-suffix) }}
