name: Production safeguard
description: Prevent accidental deployments to production environment from non master/release_* branches
inputs:
  environment:
    description: Environment
    required: true

runs:
  using: composite
  steps:
    - name: Get current branch name
      id: get-current-branch-name
      uses: viovendi/shared-github-actions/get-current-branch-name@master

    - name: Check if deployment is allowed
      shell: bash
      run: |
        if [[ "${{ inputs.environment }}" =~ ^staging[1-8]$ ]] || ([[ "${{ inputs.environment }}" =~ ^production[1-3]$ ]] && ([[ "${{ steps.get-current-branch-name.outputs.branch-name }}" = "master" ]] || [[ "${{ steps.get-current-branch-name.outputs.branch-name }}" =~ ^release_.+$ ]])); 
        then
          echo "Deployment is allowed"
          exit 0
        elif [[ "${{ inputs.environment }}" =~ ^production[1-3]$ ]]; 
        then
          echo "Production infrastructure can be deployed only from the following branches: master, release_*"
          exit 1
        else
          echo "Unrecognizable environment name"
          exit 1
        fi
