name: Build image
inputs:
  ecr-repository:
    description: ECR repository
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get current commit hash
      id: get-current-commit-hash
      uses: viovendi/shared-github-actions/get-current-commit-hash@master

    - name: Get current branch name
      id: get-current-branch-name
      uses: viovendi/shared-github-actions/get-current-branch-name@master

    - name: Build image
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        GITHUB_COMMIT_HASH: ${{ steps.get-current-commit-hash.outputs.commit-hash }}
        GITHUB_BRANCH_NAME: ${{ steps.get-current-branch-name.outputs.branch-name }}
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME || true
        docker build \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_COMMIT_HASH \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_COMMIT_HASH
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME