name: Build image
inputs:
  ecr-repository:
    description: ECR repository
    required: true
  docker-path:
    description: Docker path
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get current commit hash
      id: get-current-commit-hash
      uses: viovendi/shared-github-actions/get-current-commit-hash@master

    - name: Get current branch name
      id: get-current-branch-name
      uses: viovendi/shared-github-actions/get-current-branch-name@master

    - name: Build image
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        GITHUB_COMMIT_HASH: ${{ steps.get-current-commit-hash.outputs.commit-hash }}
        GITHUB_BRANCH_NAME: ${{ steps.get-current-branch-name.outputs.branch-name }}
        DOCKER_PATH: ${{ inputs.docker-path }}
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME || true
        docker build \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_COMMIT_HASH \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          $DOCKER_PATH
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_COMMIT_HASH
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME