name: Remove infrastructure

on:
  workflow_call:
    inputs:
      microservice-name:
        description: Microservice short name
        type: string
        required: true
      environment:
        description: Environment
        type: string
        required: true
      cf-stack-name-suffix:
        description: CloudFormation stack name suffix with trailing '-' (e.g. -database)
        type: string
        required: false
        default: ''

jobs:
  remove-infrastructure:
    name: Remove infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Remove infrastructure
        timeout-minutes: 15
        uses: viovendi/shared-github-actions/remove-infrastructure@master
        with:
          microservice-name: ${{ inputs.microservice-name }}
          environment: ${{ inputs.environment }}
          cf-stack-name-suffix: ${{ inputs.cf-stack-name-suffix }}
      
      - name: Describe infrastructure events
        if: failure()
        uses: viovendi/shared-github-actions/describe-infrastructure-events@master
        with:
          microservice-name: ${{ inputs.microservice-name }}
          environment: ${{ inputs.environment }}
          cf-stack-name-suffix: ${{ inputs.cf-stack-name-suffix }}
      
